### ISSUE TITLE
How can I use mutableai in a ipynb file

### ISSUE THREAD

**Issue by Snakebinp** [mutableai/public#1]

**Comment by yitao-mutable** [comment]
Hi, you can use our dedicated jupyter lab product at https://mutable.ai/jupyter/

Alternatively, you can enable it in the VS Code pre-release version by adding the `ipynb` filetype to the settings (you probably need a ipynb language extension too)
<img width="518" alt="image" src="https://user-images.githubusercontent.com/106548387/187260354-234ed68a-9f2f-4ce4-b3da-7cbbdf4d6810.png">
