### ISSUE TITLE
[BUG] Auto Wiki doesn't work

### ISSUE THREAD

**Issue by CodaCodr** [mutableai/public#7]
Gave trying to find your GitHub for Auto Wiki so I'm posting here.

![fa17bf6fa2c93a4726733ab2aa9316baccc2e585](https://github.com/mutableai/public/assets/436812/f5e081e2-4c5c-4c90-b267-24baea74a271)

15 hours later...

![fa17bf6fa2c93a4726733ab2aa9316baccc2e585](https://github.com/mutableai/public/assets/436812/f5bebdfb-608e-47e1-b5bf-7da8508e30d8)

Seems it can't automatically-generate docs for _any_ GH repo.

**Comment by smahsramo** [comment]
Hey it works it's possible it's due to a capitalization issue, please let us know if this works for you: https://wiki.mutable.ai/Jermolene/TiddlyWiki5

- Fellow Fine Structure Constant Appreciator

**Comment by CodaCodr** [comment]
> --Fellow Fine Structure Constant Appreciator

Ha. In something like 15 years you are the FIRST person to get it. 🥇 

I scraped the name, so it wasn't a caps issue. I'll retry later.

**Comment by CodaCodr** [comment]
Confirmed working. As for the content... impressive-looking output but quite inaccurate in so many places, it's hard (more accurately, too time-consuming) to explain. :/

**Comment by smahsramo** [comment]
Fortunately, Auto Wiki v2 is much better, stay tuned!
